# InterProScane
# VERSION 0.1
# Tracking 5.6-48.0

FROM debian:wheezy

MAINTAINER Eric Rasche, rasche.eric@yandex.ru

# make sure the package repository is up to date
RUN DEBIAN_FRONTEND=noninteractive apt-get -qq update

# Install required software
RUN DEBIAN_FRONTEND=noninteractive apt-get --no-install-recommends -y install openjdk-7-jre

